using UnityEngine;
using System;
using System.Collections.Generic;

/// <summary>
/// Quản lý câu hỏi: load từ QuizDatabase, xáo trộn (Shuffle)
/// và cung cấp câu hỏi theo từng lượt trong trận đấu.
/// Attach vào cùng GameObject với GameController.
/// </summary>
public class QuizManager : MonoBehaviour
{
    // ==================== SINGLETON ====================
    public static QuizManager Instance { get; private set; }

    // ==================== EVENTS ====================
    /// <summary>Phát khi có câu hỏi mới được load lên</summary>
    public static event Action<QuestionData> OnQuestionChanged;

    /// <summary>Phát khi đã hết toàn bộ câu hỏi trong trận</summary>
    public static event Action OnQuestionsExhausted;

    // ==================== INSPECTOR ====================
    [Header("Ngân hàng câu hỏi")]
    [SerializeField] private QuizDatabase quizDatabase;

    // ==================== INTERNAL STATE ====================
    private List<QuestionData> _shuffledQuestions;
    private int _currentIndex = -1;

    /// <summary>Câu hỏi hiện tại đang hiển thị</summary>
    public QuestionData CurrentQuestion =>
        (_currentIndex >= 0 && _shuffledQuestions != null && _currentIndex < _shuffledQuestions.Count)
            ? _shuffledQuestions[_currentIndex]
            : null;

    // ==================== LIFECYCLE ====================
    private void Awake()
    {
        if (Instance != null && Instance != this) { Destroy(gameObject); return; }
        Instance = this;
    }

    // ==================== API CÔNG KHAI ====================
    /// <summary>Khởi động quiz: shuffle và load câu đầu tiên</summary>
    /// <param name="seed">Seed để đồng bộ hóa xáo trộn giữa 2 người chơi</param>
    /// <param name="limit">Số lượng câu hỏi tối đa trong trận đấu</param>
    public void StartQuiz(int seed = -1, int limit = 10)
    {
        // BUG-11 FIX: Destroy các ScriptableObject cũ trước khi tạo mới
        if (_shuffledQuestions != null)
        {
            foreach (var q in _shuffledQuestions)
            {
                if (q != null) Destroy(q);
            }
            _shuffledQuestions.Clear();
        }

        // 1. Tự động sinh danh sách câu hỏi từ Localization Sheet nếu chưa có
        AutoGenerateDatabase();

        if (_shuffledQuestions == null || _shuffledQuestions.Count == 0)
        {
            Debug.LogError("[QuizManager] Không có câu hỏi nào được nạp!");
            return;
        }
        
        if (seed != -1)
        {
            ShuffleSeeded(_shuffledQuestions, seed);
            ShuffleAnswersInQuestions(seed); // Xáo trộn 4 đáp án bên trong mỗi câu hỏi
        }
        else
        {
            Shuffle(_shuffledQuestions);
            ShuffleAnswersInQuestions(UnityEngine.Random.Range(0, 10000));
        }

        // Giới hạn số câu hỏi theo tham số limit
        if (_shuffledQuestions.Count > limit)
        {
            _shuffledQuestions = _shuffledQuestions.GetRange(0, limit);
        }
        
        _currentIndex = -1;

        Debug.Log($"[QuizManager] Đã shuffle và chuẩn bị {_shuffledQuestions.Count} câu hỏi {(seed != -1 ? $"với seed {seed}" : "")}.");
        NextQuestion();
    }

    /// <summary>Chuyển sang câu hỏi tiếp theo</summary>
    public void NextQuestion()
    {
        _currentIndex++;

        if (_currentIndex >= _shuffledQuestions.Count)
        {
            Debug.Log("[QuizManager] Đã hết câu hỏi.");
            OnQuestionsExhausted?.Invoke();
            return;
        }

        Debug.Log($"[QuizManager] Câu hỏi [{_currentIndex + 1}/{_shuffledQuestions.Count}]");
        OnQuestionChanged?.Invoke(_shuffledQuestions[_currentIndex]);
    }

    /// <summary>Kiểm tra còn câu hỏi tiếp theo không</summary>
    public bool HasMoreQuestions() => _currentIndex + 1 < (_shuffledQuestions?.Count ?? 0);

    /// <summary>Số câu hỏi đã trả lời</summary>
    public int AnsweredCount => Mathf.Max(0, _currentIndex);

    /// <summary>Tổng số câu hỏi trong trận</summary>
    public int TotalCount => _shuffledQuestions?.Count ?? 0;

    // ==================== FISHER-YATES SHUFFLE ====================
    /// <summary>
    /// Thuật toán Fisher-Yates: xáo trộn list ngẫu nhiên không trùng lặp
    /// </summary>
    private void Shuffle(List<QuestionData> list)
    {
        for (int i = list.Count - 1; i > 0; i--)
        {
            int j = UnityEngine.Random.Range(0, i + 1);
            (list[i], list[j]) = (list[j], list[i]);
        }
    }

    /// <summary>
    /// Xáo trộn với seed cố định để đồng bộ hóa PvP
    /// </summary>
    private void ShuffleSeeded(List<QuestionData> list, int seed)
    {
        System.Random rnd = new System.Random(seed);
        for (int i = list.Count - 1; i > 0; i--)
        {
            int j = rnd.Next(0, i + 1);
            (list[i], list[j]) = (list[j], list[i]);
        }
    }

    /// <summary>
    /// Xáo trộn vị trí 4 đáp án trong MỖI câu hỏi (vì đáp án đúng luôn là index 1 trong Sheet)
    /// </summary>
    private void ShuffleAnswersInQuestions(int seed)
    {
        System.Random rnd = new System.Random(seed);
        foreach (var q in _shuffledQuestions)
        {
            if (q.answers == null || q.answers.Length == 0) continue;

            // BUG-12 FIX: Track correct index bằng index swap thay vì string compare
            int n = q.answers.Length;
            int correctIdx = q.correctAnswerIndex;

            // Fisher-Yates shuffle và track vị trí của correct answer
            for (int i = n - 1; i > 0; i--)
            {
                int j = rnd.Next(0, i + 1);
                (q.answers[i], q.answers[j]) = (q.answers[j], q.answers[i]);

                // Nếu correct answer bị swap, cập nhật index
                if (correctIdx == i) correctIdx = j;
                else if (correctIdx == j) correctIdx = i;
            }

            q.correctAnswerIndex = correctIdx;
        }
    }

    /// <summary>
    /// Tự động quét LocalizationManager để lấy toàn bộ các key bắt đầu bằng `q_`
    /// </summary>
    private void AutoGenerateDatabase()
    {
        if (LocalizationManager.Instance == null) return;

        List<string> allKeys = LocalizationManager.Instance.GetAllKeys();
        _shuffledQuestions = new List<QuestionData>();

        foreach (string key in allKeys)
        {
            if (key.StartsWith("q_"))
            {
                // Key format: q_it_001
                string[] parts = key.Split('_');
                if (parts.Length >= 3)
                {
                    string category = parts[1];
                    string qIndex = parts[2];

                    QuestionData newQ = ScriptableObject.CreateInstance<QuestionData>();
                    newQ.name = key;
                    newQ.questionText = key; // Chỉ lưu Key, không lưu nguyên văn
                    
                    // Tạo 4 key đáp án dựa theo chuẩn: a_it_001_1, a_it_001_2...
                    newQ.answers = new string[4] {
                        $"a_{category}_{qIndex}_1",
                        $"a_{category}_{qIndex}_2",
                        $"a_{category}_{qIndex}_3",
                        $"a_{category}_{qIndex}_4"
                    };

                    // Trong quy ước của bạn, số 1 luôn là đáp án đúng
                    newQ.correctAnswerIndex = 0; // Index mảng tính từ 0

                    _shuffledQuestions.Add(newQ);
                }
            }
        }
        Debug.Log($"[QuizManager] Đã tự động tạo {_shuffledQuestions.Count} câu hỏi từ bảng Localization.");
    }
}
